### ISSUE TITLE
Can’t put on AC

### ISSUE THREAD

**Issue by earth08** [Thunderbird2086/ha-custom-component-dumbir#20]
With Dumbir,
I can’t turn on AC,
When I iselect mode to cool or auto or any, my AC doesn’t turn on. 
Please guide

**Comment by Thunderbird2086** [comment]
@earth08 
Please provide your ircode yaml file.

**Comment by earth08** [comment]
Dear,
Sorry to answer late,
attached my yaml file
Please guide,
thanks

[general.txt](https://github.com/Thunderbird2086/ha-custom-component-dumbir/files/5027199/general.txt)

**Comment by Thunderbird2086** [comment]
I have reviewed you IR code file, and I don't see anything wrong. 

But, I have made small changes to yours, and you can download [general.yaml.txt](https://github.com/Thunderbird2086/ha-custom-component-dumbir/files/5040465/general.yaml.txt).

Once you download and upload to your HA, please do below
1. make sure you have the [latest release](https://github.com/Thunderbird2086/ha-custom-component-dumbir/releases/tag/0.1.3)
1. remove your climate definition from your configuration.yaml
1. restart HA
1. add climate to configuration.yaml.  It should something like below
    ```                                                 
    climate:                                            
      - platform: dumbir                                
        name: Daikin                                    
        host: xxx.xxx.xxx.xxx                           
        ir_codes: 'ir_codes/climate/general.yaml'       
        # if you have external temperature sensor       
        temperature_sensor: sensor.aqara_01_temperature 
                                                        
    switch:                                             
      # dumbir needs broadlink switch                   
      - platform: broadlink                             
        host: yyy.yyy.yyy.yyy                           
        mac: 'aa:bb:cc:dd:ee:ff'                        
    ```                                                 
1. restart HA

**Comment by Thunderbird2086** [comment]
I have reviewed you IR code file, and I don't see anything wrong. 

But, I have made small changes to yours, and you can download [general.yaml.txt](https://github.com/Thunderbird2086/ha-custom-component-dumbir/files/5040465/general.yaml.txt).

Once you download and upload the yaml file to your HA, please do below
1. make sure you have the [latest release](https://github.com/Thunderbird2086/ha-custom-component-dumbir/releases/tag/0.1.3)
1. remove your climate definition from your configuration.yaml
1. restart HA
1. add climate to configuration.yaml.  It should be something like below
    ```                                                 
    climate:                                            
      - platform: dumbir                                
        name: Daikin                                    
        host: xxx.xxx.xxx.xxx                           
        ir_codes: 'ir_codes/climate/general.yaml'       
        # if you have external temperature sensor       
        temperature_sensor: sensor.aqara_01_temperature 
                                                        
    switch:                                             
      # dumbir needs broadlink switch                   
      - platform: broadlink                             
        host: yyy.yyy.yyy.yyy                           
        mac: 'aa:bb:cc:dd:ee:ff'                        
    ```                                                 
1. restart HA

**Comment by earth08** [comment]
Still cannot put my AC on with dumbir, while I can put on my AC with smartir.

**Comment by Thunderbird2086** [comment]
Which version of HA are you using @earth08 ? 

Since 0.115, `broadlink` related services are broken.    dumbir `0.1.4` works for HA 0.115 above.

**Comment by earth08** [comment]
I am on latest HA and dumbir

**Comment by Thunderbird2086** [comment]
Please make sure that you have Broadlink Integration as below.

![Screen Shot 2020-10-02 at 18 47 06](https://user-images.githubusercontent.com/37539914/94910441-b07afb80-04df-11eb-8e3d-b000e3a690c2.png)

I found that HA 0.115 introduced Broadlink Integration, and had to remove from configuration.yaml.
Also, please make sure your configuration has `remote:` field with correct entity.

**Comment by earth08** [comment]
This is my config for my ac
```
- platform: dumbir
   name: oGen Ground dumb
   remote: remote.broadlink_living_remote
   ir_codes: 'ir_codes/climate/oGeneral_Ground.yaml'
```

**Comment by Thunderbird2086** [comment]
That's weird.  Your configuration should have worked. 

Try this.
```
- platform: dumbir
   name: oGen Ground dumb
   remote: broadlink_living_remote
   ir_codes: 'ir_codes/climate/oGeneral_Ground.yaml'
```
Please note that `remote:` field has the value of `broadlink_living_remote`.

**Comment by earth08** [comment]
> That's weird.  Your configuration should have worked. 
> 
> 
> 
> Try this.
> 
> ```
> 
> - platform: dumbir
> 
>    name: oGen Ground dumb
> 
>    remote: broadlink_living_remote
> 
>    ir_codes: 'ir_codes/climate/oGeneral_Ground.yaml'
> 
> ```
> 
> Please note that `remote:` field has the value of `broadlink_living_remote`. 
> 
> 
> 
> 

I have tried that too.
Once AC is turned on with smartir or physical remote,
I can change temperature, fan speed and can even turn off AC.
But can't turn on AC.

**Comment by Thunderbird2086** [comment]
> Once AC is turned on with smartir or physical remote,
> I can change temperature, fan speed and can even turn off AC.

It means `dumbIR` is sending command to your AC

> But can't turn on AC.

So, the issue is about your **on** command

Please make sure your config has `power:` field with `command_idle:` and `command_off`.

```
commands:
  power:
    command_idle: <base 64 encoded IR command>  # turn on AC
    command_off:  <base 64 encoded IR command>  # turn off AC
```

Or recapture *ON* command and replace existing one for `command_idle`.

Please let me know the result.
